name: Data Science - Theory and Practice
markdown: kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
remote_theme: samarsault/texture
plugins:
- jekyll-remote-theme
